# @package _global_

checkpoint_path: C:\Users\Siqi Pei\OneDrive - Delft University of Technology\CS4240 Deep Learning\deep_ev_tracker\pretrained_weights\weights_mf.ckpt
init_unrolls: 8
max_unrolls: 8
unroll_factor: 8
unroll_schedule: [700]
